name: Dockerize and Deploy

on:
  push:
    branches:
      - production

jobs:
  dockerize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: nwplus/dinubot:latest

  deploy:
    runs-on: self-hosted
    needs: dockerize

    steps:
    - name: Pull Docker image
      run: docker pull nwplus/dinubot:latest

    - name: Run Docker container
      run: |
        docker stop dinubot || true
        docker rm dinubot || true
        docker run -d -p 8000:8000 --name dinubot nwplus/dinubot:latest
