name: Refresh Secrets on Server

on:
  workflow_dispatch:

jobs:
  restart-service:
    runs-on: self-hosted
    steps:
      - name: Create .env file from secret
        run: echo '${{ secrets.ENV_FILE }}' > .env

      - name: Create service_account.json file from secret
        run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json

      - name: Restart Dinubot service
        run: |
          sudo systemctl restart dinubot
